# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('trust', ['core'])
    module.source = [
        'model/AbstractTrustCalculation.cc',
        'model/AbstractTrustEntry.cc',
        'model/trust.cc',
        'model/TrustTable.cc',
        'helper/trust-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('trust')
    module_test.source = [
        'test/trust-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'trust'
    headers.source = [
        'model/AbstractTrustCalculation.h',
        'model/AbstractTrustEntry.h',
        'model/trust.h',
        'model/TrustTable.h',
        'helper/trust-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

