## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('malicious-aodv', ['aodv', 'internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/malicious-aodv-routing-protocol.cc',
        'helper/malicious-aodv-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'malicious-aodv'
    headers.source = [
        'model/malicious-aodv-routing-protocol.h',
        'helper/malicious-aodv-helper.h',
        ]
